sonar.projectKey=larrydiamond_pyopenfixer
sonar.organization=larrydiamond-github
sonar.language=py
sonar.sources=.
sonar.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.tests=tests
sonar.python.version=3.14
# Ensure relative path for coverage to prevent SonarQube path errors
sonar.sourceEncoding=UTF-8